### PR TITLE
New Type RGB and PPM

### PR DESCRIPTION
**Pull request by dardrai**
Hi ElectronicCats Team

Thank you for your awesome CayenneLPP library. For a project we needed some additional value Types, and maybe you'll be interested in this changes.
New Values Type that we added: 

uint8_t CayenneLPP::addPPM(uint8_t channel, uint32_t value); // 1 PPM unsigned - PPM means Parts per million 1PPM = 1 * 10 ^-6 = 0.000 001
uint8_t CayenneLPP::addRGB(uint8_t channel, uint8_t r, uint8_t g, uint8_t b); // R: 255 G: 255 B: 255

addPPM(0, 401);  = 00 8F 01 91
{
  "ppm_0": 401
}
and
addRGB(0, 1, 145, 255); = 00 90 01 91 FF
{
  "rgb_0": {
    "b": 255,
    "g": 145,
    "r": 1
  }
}

### CODE REVIEW

**Comment by dardrai** [comment]
eh yes the build check fails but it shouldn't come from my changes, because I didn't change anything in the Basic_library_TTN/Basic_library_TTN.ino Example - the errors on this are mostly because of this definition, placeholders etc:

 #define loraSerial Serial1 -- some Boards don't know this Serial1 port and should be "defined"
 #define freqPlan REPLACE_ME // 'REPLACE_ME' was not declared in this scope
 TheThingsNetwork ttn(loraSerial, debugSerial, freqPlan); //in expansion of macro 'freqPlan' - because of the error above

**Comment by dardrai** [comment]
Ppm is urn:oma:lwm2m:ext:3325	3325	3325	Concentration
And rgb is urn:oma:lwm2m:ext:3335	3335	3335	Colour should i rename it to addColour and addConcentration?

**Comment by sabas1080** [comment]
Is ok for me, only
3325  change please name to "addConcentration"

3335  change please name to "addColour"

**Comment by dardrai** [comment]
Perfect I'll do that tomorrow

**Comment by dardrai** [comment]
Commits:
- Changed the Implementation according to open mobile alliance
- Fixed Typo in Concentration

 * Type                      IPSO    LPP     Hex     Data Size 
 *  Concentration       3325    125     7D      2   
 *  Colour                   3335    135     87      3     

- Code tested with with the decode / decodeTTN sketch, and with our sensors and sending it to the TTN Backend.

**Comment by sabas1080** [comment]
Thanks!

**Pull request merged**
